"""harden claim enums

Revision ID: 2152acab1afd
Revises: 0dc2385fe882
Create Date: 2026-01-08 18:33:14.553549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2152acab1afd'
down_revision: Union[str, Sequence[str], None] = '0dc2385fe882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Normalize existing rows (if any) to match the new canonical enum values.
    op.execute("UPDATE app.halal_claims SET claim_type = UPPER(claim_type) WHERE claim_type IS NOT NULL")
    op.execute("UPDATE app.halal_claims SET scope = UPPER(scope) WHERE scope IS NOT NULL")
    op.execute("UPDATE app.halal_claims SET status = UPPER(status) WHERE status IS NOT NULL")

    # Ensure server defaults are canonical
    op.alter_column(
        "halal_claims",
        "scope",
        schema="app",
        existing_type=sa.String(length=50),
        server_default=sa.text("'ALL_MENU'"),
        existing_nullable=False,
    )
    op.alter_column(
        "halal_claims",
        "status",
        schema="app",
        existing_type=sa.String(length=50),
        server_default=sa.text("'PENDING'"),
        existing_nullable=False,
    )

    # Add CHECK constraints (enforces enums at DB level while storing as VARCHAR)
    op.create_check_constraint(
        "ck_halal_claims_claim_type",
        "halal_claims",
        "claim_type IN ('ZABIHA','HALAL_CHICKEN_ONLY','NO_ALCOHOL','PORK_FREE','HALAL_MEAT_AVAILABLE')",
        schema="app",
    )
    op.create_check_constraint(
        "ck_halal_claims_scope",
        "halal_claims",
        "scope IN ('ALL_MENU','SPECIFIC_ITEMS')",
        schema="app",
    )
    op.create_check_constraint(
        "ck_halal_claims_status",
        "halal_claims",
        "status IN ('PENDING','VERIFIED','REJECTED','EXPIRED')",
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_halal_claims_status", "halal_claims", schema="app", type_="check")
    op.drop_constraint("ck_halal_claims_scope", "halal_claims", schema="app", type_="check")
    op.drop_constraint("ck_halal_claims_claim_type", "halal_claims", schema="app", type_="check")

    # Revert defaults to prior behavior (best effort)
    op.alter_column(
        "halal_claims",
        "status",
        schema="app",
        existing_type=sa.String(length=50),
        server_default=sa.text("'pending'"),
        existing_nullable=False,
    )
    op.alter_column(
        "halal_claims",
        "scope",
        schema="app",
        existing_type=sa.String(length=50),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
