"""add place_external_ids

Revision ID: 2ba16d66b41e
Revises: 017b914c3349
Create Date: 2026-01-27 15:33:01.957083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ba16d66b41e'
down_revision: Union[str, Sequence[str], None] = '017b914c3349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_external_ids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['app.places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'provider', name='uq_place_external_place_provider'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_place_external_provider_external'),
    schema='app'
    )
    # Provider is an application enum (GOOGLE/YELP/APPLE). Enforce allowed values + canonical formatting.
    op.create_check_constraint(
        'ck_place_external_ids_provider_allowed',
        'place_external_ids',
        "provider IN ('GOOGLE','YELP','APPLE')",
        schema='app',
    )
    op.create_check_constraint(
        'ck_place_external_ids_provider_upper',
        'place_external_ids',
        'provider = upper(provider)',
        schema='app',
    )
    op.create_check_constraint(
        'ck_place_external_ids_provider_trim',
        'place_external_ids',
        'provider = btrim(provider)',
        schema='app',
    )
    op.create_check_constraint(
        'ck_place_external_ids_external_id_trim',
        'place_external_ids',
        'external_id = btrim(external_id)',
        schema='app',
    )
    op.create_index(
        'ix_place_external_ids_place_id',
        'place_external_ids',
        ['place_id'],
        unique=False,
        schema='app',
    )
    op.create_index(
        'ix_place_external_provider',
        'place_external_ids',
        ['provider'],
        unique=False,
        schema='app',
    )
    op.create_index(
        'ix_place_external_external_id',
        'place_external_ids',
        ['external_id'],
        unique=False,
        schema='app',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_place_external_ids_external_id_trim', 'place_external_ids', schema='app', type_='check')
    op.drop_constraint('ck_place_external_ids_provider_trim', 'place_external_ids', schema='app', type_='check')
    op.drop_constraint('ck_place_external_ids_provider_upper', 'place_external_ids', schema='app', type_='check')
    op.drop_constraint('ck_place_external_ids_provider_allowed', 'place_external_ids', schema='app', type_='check')
    op.drop_index('ix_place_external_external_id', table_name='place_external_ids', schema='app')
    op.drop_index('ix_place_external_provider', table_name='place_external_ids', schema='app')
    op.drop_index('ix_place_external_ids_place_id', table_name='place_external_ids', schema='app')
    op.drop_table('place_external_ids', schema='app')
    # ### end Alembic commands ###
