"""add partial unique index to prevent duplicates in ownership

Revision ID: 2c831c2d6a9b
Revises: a3197d49753f
Create Date: 2026-02-03 15:04:49.857460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c831c2d6a9b'
down_revision: Union[str, Sequence[str], None] = 'a3197d49753f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ACTIVE_STATUSES = ("SUBMITTED", "NEEDS_EVIDENCE", "UNDER_REVIEW")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE UNIQUE INDEX uq_ownreq_place_email_active
        ON app.place_ownership_requests (place_id, lower(contact_email))
        WHERE status IN ('SUBMITTED','NEEDS_EVIDENCE','UNDER_REVIEW');
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS app.uq_ownreq_place_email_active;")
    # ### end Alembic commands ###
