"""create place ownership request

Revision ID: a3197d49753f
Revises: fc3bbb275ee4
Create Date: 2026-02-03 14:49:44.599638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3197d49753f'
down_revision: Union[str, Sequence[str], None] = 'fc3bbb275ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_ownership_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('requester_user_id', sa.UUID(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'SUBMITTED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['app.places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['app.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint(
            "status::text = ANY (ARRAY['SUBMITTED','NEEDS_EVIDENCE','UNDER_REVIEW','APPROVED','REJECTED','CANCELLED']::text[])",
            name="ck_place_ownership_requests_status",
        ),
    schema='app'
    )

    op.create_index(
        "ix_place_ownership_requests_place_id",
        "place_ownership_requests",
        ["place_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_place_ownership_requests_status",
        "place_ownership_requests",
        ["status"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_place_ownership_requests_created_at",
        "place_ownership_requests",
        ["created_at"],
        unique=False,
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_place_ownership_requests_created_at", table_name="place_ownership_requests", schema="app")
    op.drop_index("ix_place_ownership_requests_status", table_name="place_ownership_requests", schema="app")
    op.drop_index("ix_place_ownership_requests_place_id", table_name="place_ownership_requests", schema="app")
    op.drop_table('place_ownership_requests', schema='app')
    # ### end Alembic commands ###
