"""add composite index for scale

Revision ID: cc91cbdccaee
Revises: 2c831c2d6a9b
Create Date: 2026-02-03 16:31:58.259382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc91cbdccaee'
down_revision: Union[str, Sequence[str], None] = '2c831c2d6a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE INDEX ix_ownreq_status_created_at_desc
        ON app.place_ownership_requests (status, created_at DESC);
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS app.ix_ownreq_status_created_at_desc;")
    # ### end Alembic commands ###
