"""core users orgs place_owners

Revision ID: f57ffd81fc5d
Revises: ce280a089baf
Create Date: 2026-01-08 17:48:27.568852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f57ffd81fc5d'
down_revision: Union[str, Sequence[str], None] = 'ce280a089baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), server_default=sa.text("'CONSUMER'"), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text("true"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('place_owners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), server_default=sa.text("'OWNER'"), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['app.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['app.places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'organization_id', name='uq_place_owner_place_org'),
    schema='app'
    )
    # Indexes
    op.create_index(
        "ix_users_email",
        "users",
        ["email"],
        unique=True,
        schema="app",
    )

    op.create_index(
        "ix_place_owners_place_id",
        "place_owners",
        ["place_id"],
        schema="app",
    )

    op.create_index(
        "ix_place_owners_organization_id",
        "place_owners",
        ["organization_id"],
        schema="app",
    )

    op.create_check_constraint(
        "ck_users_role",
        "users",
        "role IN ('CONSUMER','OWNER','VERIFIER','ADMIN')",
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_place_owners_organization_id", table_name="place_owners", schema="app")
    op.drop_index("ix_place_owners_place_id", table_name="place_owners", schema="app")
    op.drop_index("ix_users_email", table_name="users", schema="app")

    op.drop_constraint('ck_users_role', table_name='users', schema="app")

    op.drop_table('place_owners', schema='app')
    op.drop_table('users', schema='app')
    op.drop_table('organizations', schema='app')
    # ### end Alembic commands ###
