"""add app.place_events

Revision ID: fc3bbb275ee4
Revises: 089318ec9422
Create Date: 2026-01-29 14:33:37.235018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc3bbb275ee4'
down_revision: Union[str, Sequence[str], None] = '089318ec9422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['place_id'], ['app.places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )

    op.create_index(
        "ix_place_events_place_id",
        "place_events",
        ["place_id"],
        schema="app",
    )
    op.create_index(
        "ix_place_events_actor_user_id",
        "place_events",
        ["actor_user_id"],
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_place_events_actor_user_id", table_name="place_events", schema="app")
    op.drop_index("ix_place_events_place_id", table_name="place_events", schema="app")
    
    op.drop_table('place_events', schema='app')
    # ### end Alembic commands ###
