import type { MetadataRoute } from "next";

import { SITE_URL } from "@/lib/branding";

/**
 * /robots.txt — generated by the Next.js App Router.
 *
 * Allow everything publicly browseable, disallow the auth + personal
 * areas (signed-in surfaces shouldn't be in the search index — they
 * 401 to crawlers and have nothing to offer them anyway).
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: ["/"],
        disallow: ["/login", "/signup", "/preferences", "/disputes"],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
