import type { MetadataRoute } from "next";

import { SITE_URL } from "@/lib/branding";

/**
 * /sitemap.xml — generated by the Next.js App Router.
 *
 * v1 lists the static surfaces only. Per-place URLs (`/places/{id}`)
 * need a sitemap-friendly enumeration endpoint on the API since
 * `GET /places` requires either a query string or geo radius — there
 * is no "list everything" on the public catalog by design. Adding
 * `GET /places/sitemap` (or paginated) on the backend is the next
 * step; once it lands, fetch + spread the rows into the array
 * below.
 *
 * `lastModified` is set to the build time so a redeploy nudges
 * crawlers to recheck. Static surfaces don't shift often, so a low
 * `changeFrequency` is fine.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();
  return [
    {
      url: `${SITE_URL}/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 1.0,
    },
    {
      url: `${SITE_URL}/preferences`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 0.3,
    },
  ];
}
