from enum import StrEnum

class ExternalIdProvider(StrEnum):
    GOOGLE = "GOOGLE"
    YELP = "YELP"
    APPLE = "APPLE"


class PlaceEventType(StrEnum):
    CREATED = "CREATED"
    EDITED = "EDITED"
    DELETED = "DELETED"
    RESTORED = "RESTORED"
    OWNERSHIP_GRANTED = "OWNERSHIP_GRANTED"
    OWNERSHIP_REQUEST_REJECTED = "OWNERSHIP_REQUEST_REJECTED"
    OWNERSHIP_REQUEST_NEEDS_EVIDENCE = "OWNERSHIP_REQUEST_NEEDS_EVIDENCE"