/**
 * Trust Halal brand mark.
 *
 * The same artwork as the favicon and app icon (app/icon.svg, generated by
 * brand-assets/generate_icons.py): the eight-point rub-el-hizb star with the
 * verification check knocked out, on the emerald tile. The header used to
 * render a bare checkmark in a rounded square, which didn't match the icon in
 * the browser tab or on the installed-app home screen.
 *
 * Colours are fixed (not theme tokens) on purpose — a logo should read the
 * same on every surface. Rounded corners and the star are baked into the SVG,
 * so no wrapping tile is needed; size via `className` (default h-8 w-8).
 */
export function BrandMark({ className = "h-8 w-8" }: { className?: string }) {
  return (
    <svg
      aria-hidden="true"
      className={`${className} shrink-0 drop-shadow-sm`}
      viewBox="0 0 1024 1024"
      xmlns="http://www.w3.org/2000/svg"
    >
      <rect width="1024" height="1024" rx="230" fill="#0E7C66" />
      <path
        d="M 650.5 177.6 L 693.0 331.0 L 846.4 373.5 L 768.0 512.0 L 846.4 650.5 L 693.0 693.0 L 650.5 846.4 L 512.0 768.0 L 373.5 846.4 L 331.0 693.0 L 177.6 650.5 L 256.0 512.0 L 177.6 373.5 L 331.0 331.0 L 373.5 177.6 L 512.0 256.0 Z"
        fill="#F6F2E9"
        stroke="#F6F2E9"
        strokeWidth={12}
        strokeLinejoin="round"
      />
      <path
        d="M 400 522 L 476 598 L 640 424"
        fill="none"
        stroke="#0E7C66"
        strokeWidth={82}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}
