/**
 * Shared page chrome for trusthalal.org — header, footer, brand
 * mark, and the small arrow icon. Extracted from the landing page
 * when /ethics arrived so both pages render identical chrome
 * without copy-paste drift.
 *
 * Server components only; zero client JS.
 */

import {
  ADMIN_URL,
  CONSUMER_URL,
  CONTACT_EMAIL,
  ETHICS_PATH,
  FACEBOOK_URL,
  INSTAGRAM_URL,
  OWNER_URL,
  PRIVACY_PATH,
  DELETE_ACCOUNT_PATH,
  TERMS_PATH,
  TIKTOK_URL,
  SUPPORT_PATH,
  VERIFIER_URL,
} from "@/lib/links";

/**
 * Trust Halal brand mark — the same artwork as the favicon and app icon
 * (app/icon.svg, generated by brand-assets/generate_icons.py): the eight-point
 * rub-el-hizb star with the verification check knocked out, on the emerald
 * tile. It used to be a bare checkmark in a rounded square, which didn't match
 * the icon anyone saw in their browser tab or on their home screen.
 *
 * Colours are fixed (not theme tokens) on purpose — a logo should read the
 * same on every surface. The rounded corners and star are baked into the SVG,
 * so no wrapping tile is needed; size via the h-/w- classes.
 */
export function BrandMark() {
  return (
    <svg
      aria-hidden="true"
      className="h-8 w-8 shrink-0 drop-shadow-sm"
      viewBox="0 0 1024 1024"
      xmlns="http://www.w3.org/2000/svg"
    >
      <rect width="1024" height="1024" rx="230" fill="#0E7C66" />
      <path
        d="M 650.5 177.6 L 693.0 331.0 L 846.4 373.5 L 768.0 512.0 L 846.4 650.5 L 693.0 693.0 L 650.5 846.4 L 512.0 768.0 L 373.5 846.4 L 331.0 693.0 L 177.6 650.5 L 256.0 512.0 L 177.6 373.5 L 331.0 331.0 L 373.5 177.6 L 512.0 256.0 Z"
        fill="#F6F2E9"
        stroke="#F6F2E9"
        strokeWidth={12}
        strokeLinejoin="round"
      />
      <path
        d="M 400 522 L 476 598 L 640 424"
        fill="none"
        stroke="#0E7C66"
        strokeWidth={82}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

export function ArrowIcon() {
  return (
    <svg
      aria-hidden="true"
      width="15"
      height="15"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2.25"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  );
}

/**
 * Site header. Section anchors are rooted at "/#…" so they work
 * from any page, not just the landing.
 */
export function Header() {
  return (
    <header className="mb-16 flex items-center justify-between gap-4 sm:mb-24">
      <a href="/" className="flex items-center gap-2.5 transition hover:opacity-80">
        <BrandMark />
        <span className="text-xl font-semibold tracking-tight text-ink sm:text-2xl">
          Trust Halal
        </span>
      </a>
      <div className="flex items-center gap-5">
        <nav
          aria-label="Sections"
          className="hidden items-center gap-5 text-sm text-sub md:flex"
        >
          <a href="/#how-it-works" className="transition hover:text-ink">
            How it works
          </a>
          <a href="/#tiers" className="transition hover:text-ink">
            Verification tiers
          </a>
          <a href={ETHICS_PATH} className="transition hover:text-ink">
            Ethics
          </a>
          <a
            href={`mailto:${CONTACT_EMAIL}`}
            className="transition hover:text-ink"
          >
            Contact
          </a>
        </nav>
        <a
          href={CONSUMER_URL}
          className="inline-flex items-center gap-1.5 rounded-full bg-accent px-4 py-2 text-sm font-medium text-onaccent shadow-sm transition hover:bg-accent-deep"
        >
          Find halal food near you
          <ArrowIcon />
        </a>
      </div>
    </header>
  );
}

export function Footer() {
  return (
    <footer className="border-t border-line bg-surface">
      <div className="mx-auto max-w-5xl px-6 py-12">
        <div className="mb-10 grid gap-10 sm:grid-cols-[1.4fr_1fr_1fr]">
          <div>
            <div className="mb-3 flex items-center gap-2.5">
              <BrandMark />
              <span className="text-xl font-semibold tracking-tight text-ink">
                Trust Halal
              </span>
            </div>
            <p className="max-w-sm text-sm leading-relaxed text-sub">
              The open verification platform for halal restaurants.
              Independent of any specific certifying body; we accept
              certificates from any recognized halal authority.
              Verification stays free for restaurants.
            </p>
            <SocialLinks />
          </div>
          <FooterColumn
            title="Platform"
            links={[
              { label: "halalfoodnearme.com", href: CONSUMER_URL },
              { label: "Owner portal", href: OWNER_URL },
              { label: "Verifier program", href: VERIFIER_URL },
              { label: "Admin", href: ADMIN_URL },
            ]}
          />
          <FooterColumn
            title="Company"
            links={[
              { label: "AI ethics", href: ETHICS_PATH },
              { label: "Privacy", href: PRIVACY_PATH },
              { label: "Terms", href: TERMS_PATH },
              { label: "Delete account", href: DELETE_ACCOUNT_PATH },
              { label: "Support", href: SUPPORT_PATH },
              {
                label: CONTACT_EMAIL,
                href: `mailto:${CONTACT_EMAIL}`,
              },
            ]}
          />
        </div>
        <p className="border-t border-line pt-6 text-xs text-sub">
          © {new Date().getFullYear()} Trust Halal. Community-built,
          Muslim-led.
        </p>
      </div>
    </footer>
  );
}

function FooterColumn({
  title,
  links,
}: {
  title: string;
  links: Array<{ label: string; href: string }>;
}) {
  return (
    <nav aria-label={title}>
      <h3 className="mb-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-sub">
        {title}
      </h3>
      <ul className="space-y-2 text-sm text-sub">
        {links.map((l) => (
          <li key={l.href}>
            <a href={l.href} className="transition hover:text-ink hover:underline">
              {l.label}
            </a>
          </li>
        ))}
      </ul>
    </nav>
  );
}

/**
 * Social presence — icon links to the brand's Instagram, TikTok, and
 * Facebook. Brand glyphs are single-path (simple-icons) so each is one
 * <path fill="currentColor">; colour inherits the footer text tone and
 * lifts to --ink on hover, matching the footer's other links.
 */
const SOCIALS: ReadonlyArray<{ label: string; href: string; path: string }> = [
  {
    label: "Instagram",
    href: INSTAGRAM_URL,
    path: "M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z",
  },
  {
    label: "TikTok",
    href: TIKTOK_URL,
    path: "M12.525.02c1.31-.02 2.61-.01 3.91-.02.08 1.53.63 3.09 1.75 4.17 1.12 1.11 2.7 1.62 4.24 1.79v4.03c-1.44-.05-2.89-.35-4.2-.97-.57-.26-1.1-.59-1.62-.93-.01 2.92.01 5.84-.02 8.75-.08 1.4-.54 2.79-1.35 3.94-1.31 1.92-3.58 3.17-5.91 3.21-1.43.08-2.86-.31-4.08-1.03-2.02-1.19-3.44-3.37-3.65-5.71-.02-.5-.03-1-.01-1.49.18-1.9 1.12-3.72 2.58-4.96 1.66-1.44 3.98-2.13 6.15-1.72.02 1.48-.04 2.96-.04 4.44-.99-.32-2.15-.23-3.02.37-.63.41-1.11 1.04-1.36 1.75-.21.51-.15 1.07-.14 1.61.24 1.64 1.82 3.02 3.5 2.87 1.12-.01 2.19-.66 2.77-1.61.19-.33.4-.67.41-1.06.1-1.79.06-3.57.07-5.36.01-4.03-.01-8.05.02-12.07z",
  },
  {
    label: "Facebook",
    href: FACEBOOK_URL,
    path: "M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z",
  },
];

function SocialLinks() {
  return (
    <div className="mt-5 flex items-center gap-4">
      {SOCIALS.map((s) => (
        <a
          key={s.href}
          href={s.href}
          target="_blank"
          rel="noopener noreferrer"
          aria-label={s.label}
          title={s.label}
          className="text-sub transition hover:text-ink"
        >
          <svg
            width="20"
            height="20"
            viewBox="0 0 24 24"
            fill="currentColor"
            aria-hidden="true"
          >
            <path d={s.path} />
          </svg>
        </a>
      ))}
    </div>
  );
}
