#!/usr/bin/env python3
"""Regenerate every Trust Halal icon asset from one definition.

    python3 brand-assets/generate_icons.py

## Why a script and not hand-drawn files

The mark exists in eleven places across four apps. Hand-editing them drifts —
that's exactly how the old crescent ended up with a different ground colour on
the web than in the mobile theme. Everything here derives from `STAR_R`,
`CHECK` and `GROUND` below; change one and rerun.

## The two things that are easy to get wrong

**The check is a knockout, not a black stroke.** In the flat app icon it's
painted in the ground colour, which is fine because the ground is opaque. In
the three transparent assets — Android adaptive foreground, notification icon,
and the single-colour mark — it must be *actually transparent*, so those are
drawn with cairo using `OPERATOR_CLEAR`. Painting it black instead looks
correct over a known background and breaks in the two places that matter: an
Android launcher plate of any colour, and the notification tray, which keeps
alpha only and would swallow a painted check into a solid blob.

SVG `mask` expresses this correctly and browsers honour it, but ImageMagick's
built-in renderer silently ignores both `mask` and `textPath` — so the PNGs
are rendered with cairo rather than by rasterising the SVG.

**The adaptive foreground is smaller than the app icon.** Android masks it to
a circle or squircle and crops roughly the outer third, so the star is drawn at
`ADAPTIVE_R` rather than `STAR_R`. At full size the launcher shears the points
off. Its plate colour lives in `app.json` as
`android.adaptiveIcon.backgroundColor` and must equal `GROUND`, because the
check knocks through the foreground onto it.
"""
from __future__ import annotations

import math
import shutil
import subprocess
from pathlib import Path

import cairo

# --- the mark --------------------------------------------------------------
# Eight-point star at the rub-el-hizb proportion: inner/outer = 1/sqrt(2) is
# exactly two overlapping squares. Lower ratios get spiky and lose mass at
# small sizes.
RATIO = 1 / math.sqrt(2)
CANVAS = 1024
STAR_R = 362          # app icon
ADAPTIVE_R = 268      # Android safe zone — see module docstring
CORNER = 12           # join softening; higher rounds the points away
CHECK_W = 82
CHECK = [(400, 522), (476, 598), (640, 424)]
RX = 230              # rounded-square corner radius

# Ground is #0E7C66, not the older #0E9F6E. Cream on #0E9F6E measures 3.03:1;
# on #0E7C66 it's 4.59:1, and this mark leans on that separation once the
# check is cut out of the star. This is the ICON ground only — the in-app
# accent token is still #0E9F6E and is deliberately left alone.
GROUND = "#0E7C66"
CREAM = "#F6F2E9"

ROOT = Path(__file__).resolve().parent.parent
ICON = ROOT / "brand-assets" / "icon"


def _hex(c: str) -> tuple[float, float, float]:
    c = c.lstrip("#")
    return tuple(int(c[i:i + 2], 16) / 255 for i in (0, 2, 4))  # type: ignore[return-value]


def star_points(r: float, cx: float = 512, cy: float = 512, rot: float = math.pi / 8):
    return [
        (cx + (r if i % 2 == 0 else r * RATIO) * math.sin(rot + i * math.pi / 8),
         cy - (r if i % 2 == 0 else r * RATIO) * math.cos(rot + i * math.pi / 8))
        for i in range(16)
    ]


def star_path(r: float) -> str:
    p = star_points(r)
    return (f"M {p[0][0]:.1f} {p[0][1]:.1f} "
            + " ".join(f"L {x:.1f} {y:.1f}" for x, y in p[1:]) + " Z")


HEADER = (
    '<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024"\n'
    '     viewBox="0 0 1024 1024" role="img" aria-label="Trust Halal">\n'
    "  <!-- GENERATED by brand-assets/generate_icons.py — do not hand-edit.\n"
    "       Eight-point star (rub-el-hizb proportion) with a verification\n"
    "       check knocked out of it. -->\n"
)


def svg_flat(rounded: bool) -> str:
    rx = f' rx="{RX}"' if rounded else ""
    return (HEADER
            + f'  <rect width="1024" height="1024"{rx} fill="{GROUND}"/>\n'
            + f'  <path d="{star_path(STAR_R)}" fill="{CREAM}" stroke="{CREAM}"'
              f' stroke-width="{CORNER}" stroke-linejoin="round"/>\n'
            + f'  <path d="M {CHECK[0][0]} {CHECK[0][1]} L {CHECK[1][0]} {CHECK[1][1]}'
              f' L {CHECK[2][0]} {CHECK[2][1]}" fill="none" stroke="{GROUND}"'
              f' stroke-width="{CHECK_W}" stroke-linecap="round" stroke-linejoin="round"/>\n'
            + "</svg>\n")


def svg_silhouette() -> str:
    """16px variant. At that size the check is about two pixels of stroke and
    reads as a scratch across the star, so the small mark drops it."""
    return (HEADER
            + f'  <rect width="1024" height="1024" rx="{RX}" fill="{GROUND}"/>\n'
            + f'  <path d="{star_path(STAR_R)}" fill="{CREAM}" stroke="{CREAM}"'
              f' stroke-width="{CORNER}" stroke-linejoin="round"/>\n</svg>\n')


def svg_knockout(fill: str, r: float) -> str:
    """Transparent-ground variant. Correct per spec; browsers honour the mask.
    The PNGs are still produced by cairo — see module docstring."""
    k = CORNER * r / STAR_R
    sc = r / STAR_R
    chk = (f'M {CHECK[0][0]} {CHECK[0][1]} L {CHECK[1][0]} {CHECK[1][1]}'
           f' L {CHECK[2][0]} {CHECK[2][1]}')
    return (HEADER
            + '  <defs>\n    <mask id="knock" maskUnits="userSpaceOnUse"'
              ' x="0" y="0" width="1024" height="1024">\n'
            + f'      <path d="{star_path(r)}" fill="#fff" stroke="#fff"'
              f' stroke-width="{k:.1f}" stroke-linejoin="round"/>\n'
            + f'      <path d="{chk}" fill="none" stroke="#000" stroke-width="{CHECK_W}"\n'
              f'            stroke-linecap="round" stroke-linejoin="round"\n'
              f'            transform="translate(512,512) scale({sc:.4f}) translate(-512,-512)"/>\n'
            + '    </mask>\n  </defs>\n'
            + f'  <path d="{star_path(r)}" fill="{fill}" stroke="{fill}"'
              f' stroke-width="{k:.1f}" stroke-linejoin="round" mask="url(#knock)"/>\n</svg>\n')


def render_knockout(dest: Path, r: float, rgb: tuple[float, float, float], size: int = 1024):
    """cairo, because the check has to be genuinely transparent."""
    surf = cairo.ImageSurface(cairo.FORMAT_ARGB32, size, size)
    cr = cairo.Context(surf)
    cr.scale(size / CANVAS, size / CANVAS)
    sc = r / STAR_R
    cr.set_source_rgb(*rgb)
    cr.set_line_join(cairo.LINE_JOIN_ROUND)
    cr.set_line_width(CORNER * sc)
    pts = star_points(r)
    cr.move_to(*pts[0])
    for p in pts[1:]:
        cr.line_to(*p)
    cr.close_path()
    cr.fill_preserve()
    cr.stroke()
    cr.set_operator(cairo.OPERATOR_CLEAR)
    cr.set_line_width(CHECK_W * sc)
    cr.set_line_cap(cairo.LINE_CAP_ROUND)
    cr.set_line_join(cairo.LINE_JOIN_ROUND)
    tx = lambda x, y: (512 + (x - 512) * sc, 512 + (y - 512) * sc)  # noqa: E731
    cr.move_to(*tx(*CHECK[0]))
    for p in CHECK[1:]:
        cr.line_to(*tx(*p))
    cr.stroke()
    dest.parent.mkdir(parents=True, exist_ok=True)
    surf.write_to_png(str(dest))


def rasterise(src: Path, dest: Path, size: int):
    dest.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(["convert", "-background", "none", "-density", "600",
                    str(src), "-resize", f"{size}x{size}", str(dest)], check=True)


def main() -> int:
    ICON.mkdir(parents=True, exist_ok=True)

    (ICON / "trust-halal-icon.svg").write_text(svg_flat(rounded=True))
    (ICON / "trust-halal-icon-square.svg").write_text(svg_flat(rounded=False))
    (ICON / "trust-halal-icon-small.svg").write_text(svg_silhouette())
    (ICON / "trust-halal-mark-white.svg").write_text(svg_knockout("#FFFFFF", STAR_R))
    (ICON / "adaptive-foreground.svg").write_text(svg_knockout(CREAM, ADAPTIVE_R))
    (ICON / "notification-icon.svg").write_text(svg_knockout("#FFFFFF", ADAPTIVE_R))

    for s in (120, 180, 512, 1024):
        rasterise(ICON / "trust-halal-icon.svg", ICON / f"icon-rounded-{s}.png", s)
    for s in (256, 512, 1024):
        rasterise(ICON / "trust-halal-icon-square.svg", ICON / f"icon-square-{s}.png", s)
    rasterise(ICON / "trust-halal-icon.svg", ICON / "favicon-48.png", 48)
    rasterise(ICON / "trust-halal-icon.svg", ICON / "favicon-32.png", 32)
    rasterise(ICON / "trust-halal-icon-small.svg", ICON / "favicon-16.png", 16)

    render_knockout(ICON / "mark-white-1024.png", STAR_R, (1, 1, 1))
    render_knockout(ICON / "adaptive-foreground-1024.png", ADAPTIVE_R, _hex(CREAM))
    render_knockout(ICON / "notification-icon-1024.png", ADAPTIVE_R, (1, 1, 1))

    # --- distribute --------------------------------------------------------
    # Next.js serves app/icon.svg and app/apple-icon.png automatically.
    for app in ("brand", "consumer"):
        shutil.copyfile(ICON / "trust-halal-icon.svg",
                        ROOT / f"apps/{app}/src/app/icon.svg")
        rasterise(ICON / "trust-halal-icon.svg",
                  ROOT / f"apps/{app}/src/app/apple-icon.png", 180)

    # Expo. The iOS asset catalogue and Android res/ are prebuild output and
    # gitignored, so these three are the only mobile sources that matter.
    rasterise(ICON / "trust-halal-icon-square.svg",
              ROOT / "apps/mobile/assets/icon.png", 1024)
    render_knockout(ROOT / "apps/mobile/assets/adaptive-icon.png",
                    ADAPTIVE_R, _hex(CREAM))
    render_knockout(ROOT / "apps/mobile/assets/notification-icon.png",
                    ADAPTIVE_R, (1, 1, 1))

    # Splash. Transparent ground, cream star, check knocked through to
    # whatever sits behind — which the plugin config sets to GROUND, so the
    # check reads the same colour it does on the app icon and the launch
    # image is visibly the same mark rather than a lookalike.
    #
    # STAR_R, not ADAPTIVE_R: nothing crops a splash. ADAPTIVE_R exists only
    # because Android shears the outer third off a launcher icon.
    #
    # Deliberately NOT icon.png. That file has its own opaque GROUND square
    # baked in, so any future drift between it and the plugin's
    # backgroundColor would show up as a faint square outline on the launch
    # screen — the kind of thing nobody notices until it ships.
    render_knockout(ROOT / "apps/mobile/assets/splash-icon.png",
                    STAR_R, _hex(CREAM))

    print("regenerated icon assets from GROUND=%s STAR_R=%d" % (GROUND, STAR_R))
    print("reminder: app.json android.adaptiveIcon.backgroundColor AND the")
    print("          expo-splash-screen backgroundColor must both equal", GROUND)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
